[project]
name = "ray-pbt-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.9.2",
    "ray[tune]>=2.37.0",
]
